# Simulation parameters for Example 1 in Stress Test paper.
default:
  use_version: "1.0"
  cran_packages:
    - "cobalt"
    - "devtools"
    - "digest"
    - "dplyr"
    - "ggplot2"
    - "ggsci"
    - "here"
    - "kableExtra"
    - "labelled"
    - "rpact"
    - "stringr"
    - "table1"
    - "tidyr"
    - "xfun"
  github_packages:
    - "jbetz-jhu/impart"




# knitr parameters
report_parameters:
  opts_chunk:
    collapse: TRUE
    echo: FALSE
    message: TRUE
    error: TRUE
    purl: FALSE
    results: "asis"
    fig_path: "figures"
    fig_width: 12
    fig_height: 12
    fig_align: "center"
    out_width: "80%"
    dpi: 300
    
  ggplot_parameters:
    axis_text_size: 16
    axis_text_face: "plain"
    axis_title_size: 16
    axis_title_face: "plain"
    facet_text_size: 16
    facet_text_face: "plain"
    plot_title_size: 20
    plot_title_face: "bold"
    legend_text_size: 17
    legend_text_face: "bold"
    legend_title_size: 16
    legend_title_face: "bold"
    legend_position: "bottom"




# MISTIE III Example Parameters
binary_example_mistie:
  example_data_file_name: "Simulated_MISTIE_III.Rdata"
  example_output_file_name: "Simulated_MISTIE_III_output.Rdata"
  example_output_file_name_gsd: "Simulated_MISTIE_III_output_gsd.Rdata"
  rng_seed: 12345
  alpha_design: 0.05
  power_design: 0.80
  test_sides: 2
  p0_design: 0.25
  p1_design: 0.38
  pr_missing: 0.20
  enroll_start: "2013-12-30"
  enroll_end: "2017-08-15"
  information_rates:
    - 0.50
    - 0.75
    - 1.00
  type_of_design_asof: "asOF"
  type_beta_spending_asof: "none"
  type_of_design_asof_bsof: "asOF"
  type_beta_spending_asof_bsof: "bsOF"